apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a9f17b7lw-go
  janus-idp.io/tekton: a9f17b7lw-go
  backstage.io/kubernetes-id: a9f17b7lw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a9f17b7lw-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
