apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: a9f17b7lw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a9f17b7lw-go 
  name: a9f17b7lw-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: a9f17b7lw-go
    weight: 100 
